### ISSUE TITLE
FullyQualifiedName not resolved for classes in same package

### ISSUE THREAD

**Issue by novoj** [paul-hammant/qdox#12] opened 2016-09-17 16:43 UTC
I have class:

``` java
package com.fg.rtdoc.test;

public class Test extends Extend implements Iface {

}
```

And build it by:

``` java
JavaProjectBuilder builder = new JavaProjectBuilder();
return builder.getClassByName(name);
```

(.java file are available on current classpath - so that com.thoughtworks.qdox.library.ClassLoaderLibrary#resolveJavaClass finds and returns it)

Then when calling JavaClass.getInterfaces().get(0).getFullyQualifiedName() I obtain `Iface` instead of `com.fg.rtdoc.test.Iface`. I know, that plain Iface would be ok in this case, but QDox should try to load both classes `Iface` and when not found `com.fg.rtdoc.test.Iface` but when I debug the code I saw no attempt of doing so.

It works only when I manually add imports for those classes which are not really necessary for Java compiler.

**Comment by rfscholte** [comment] 2016-12-18 16:20
I've committed a unittest and cannot reproduce it. Feel free to reopen if you can adjust the test to reproduce it.

**Closed by rfscholte** 2016-12-18 16:20 UTC
