### ISSUE TITLE
A Comment After An extends/implements Clause Results In A ParseException

### ISSUE THREAD

**Issue by fearghalom** [paul-hammant/qdox#17] opened 2017-03-27 14:57 UTC
If a Java comment, either a block or line comment, appears after an 'extends' or 'implements' clause in the class declaration, a ParseException is thrown (See the stacktrace below).

`public class Foo extends Bar
//extends FooBar
{ ....
}`

`public class Foo implements IBar
/* extends FooBar */
{ ....
}`

_Exception in thread "main" com.thoughtworks.qdox.parser.ParseException: syntax error @[21,3] in file:Test.java
	at com.thoughtworks.qdox.parser.impl.Parser.yyerror(Parser.java:1768)
	at com.thoughtworks.qdox.parser.impl.Parser.yyparse(Parser.java:1890)
	at com.thoughtworks.qdox.parser.impl.Parser.parse(Parser.java:1749)
	at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:232)
	at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:209)
	at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:159)
	at com.thoughtworks.qdox.library.SortedClassLibraryBuilder.addSource(SortedClassLibraryBuilder.java:174)
	at com.thoughtworks.qdox.JavaProjectBuilder.addSource(JavaProjectBuilder.java:151)
	at com.thoughtworks.qdox.JavaProjectBuilder$2.visitFile(JavaProjectBuilder.java:224)
	at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:103)
	at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:91)
	at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:91)
	at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:91)
	at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:91)
	at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:91)
	at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:91)
	at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:91)
	at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:91)
	at com.thoughtworks.qdox.directorywalker.DirectoryScanner.scan(DirectoryScanner.java:81)
	at com.thoughtworks.qdox.JavaProjectBuilder.addSourceTree(JavaProjectBuilder.java:218)
	at com.thoughtworks.qdox.JavaProjectBuilder.addSourceTree(JavaProjectBuilder.java:205)
	at Test.generateCode(Test.java:28)
	at Test.main(Test.java:17)_

**Comment by rfscholte** [comment] 2017-03-28 18:29
This is a duplicate of #16

**Closed by rfscholte** 2017-03-28 18:29 UTC
