### ISSUE TITLE
Qdox 2.0-M5 fails to parse DefaultToolchain.java in Maven 3.5.0

### ISSUE THREAD

**Issue by ebourg** [paul-hammant/qdox#21] opened 2017-07-03 15:33 UTC
Hi,

When rebuilding Maven 3.5.0 with the latest version of Qdox I got the following error:

    Error generating metadata: : Failed to extract descriptors: syntax error@[37,43] in file:/build/maven-3.5.0/maven-core/src/main/java/org/apache/maven/toolchain/DefaultToolchain.java

Here is the relevant line in DefaultToolchain:
https://github.com/apache/maven/blob/maven-3.5.0/maven-core/src/main/java/org/apache/maven/toolchain/DefaultToolchain.java#L37

Removing the comment at the end of the line 37 fixes the issue. This file was still parsed properly with Qdox 2.0-M3.

**Comment by rfscholte** [comment] 2017-07-03 17:20
Duplicate of #17 and is fixed with the next release.

**Closed by rfscholte** 2017-07-03 17:20 UTC
Labels: duplicate
