### ISSUE TITLE
Fully qualified names of inner classes

### ISSUE THREAD

**Issue by Tillerino** [paul-hammant/qdox#6] opened 2015-10-08 12:39 UTC
```
class A {
    class B {
    }
}
```

In qdox, the fully qualified class name of `B` is `A$B`, however according to the [Java Specification](https://docs.oracle.com/javase/specs/jls/se7/html/jls-6.html#jls-6.7):

> A member class or member interface M of another class or interface C has a fully qualified name if and only if C has a fully qualified name.
> In that case, the fully qualified name of M consists of the fully qualified name of C, followed by ".", followed by the simple name of M.

So in the above case, the fully qualified class name of `B` is `A.B`.

**Comment by rfscholte** [comment] 2016-08-13 13:24
This is quite a painfull conclusion since QDox uses the `$` probably since the beginning. I've introduced canonicalName a long time ago to have a better directive to classes in code, but that one might not follow the specs completely.
There's probably still a need for the $-syntax to easily discover the wrapping class. Not sure what to do with this, since I can't oversee the impact by projects using QDox.

**Comment by rfscholte** [comment] 2016-12-19 21:05
I guess 2.0 would be the right moment to rename it to binaryName (https://docs.oracle.com/javase/specs/jls/se8/html/jls-13.html#jls-13.1) and to work out the canonical and fully qualified name again

**Comment by ebourg** [comment] 2017-08-30 13:49
Hi, I'm not sure this is related to this issue but I stumbled on an error related to inner classes when building Avro with qdox 2.0-M5 instead of qdox 2.0-M3. The build fails with this error:

    [INFO] Generating parameter names from /home/ebourg/avro-java/lang/java/avro/src/test/java to /home/ebourg/avro-java/lang/java/avro/target/test-classes
    [INFO] ------------------------------------------------------------------------
    [INFO] Reactor Summary:
    [INFO]
    [INFO] Apache Avro Toplevel ............................... SUCCESS [  0.002 s]
    [INFO] Apache Avro Java ................................... SUCCESS [  0.048 s]
    [INFO] Apache Avro ........................................ FAILURE [  2.745 s]
    [INFO] Apache Avro Compiler ............................... SKIPPED
    [INFO] Apache Avro Maven Plugin ........................... SKIPPED
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 3.284 s
    [INFO] Finished at: 2017-08-30T14:51:03+02:00
    [INFO] Final Memory: 24M/281M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal com.thoughtworks.paranamer:paranamer-maven-plugin:2.8:generate (paranamer-test) on project avro: Failed to generate parameter names from /home/ebourg/avro-java/lang/java/avro/src/test/java: /home/ebourg/avro-java/lang/java/avro/target/test-classes/org/apache/avro/reflect/TestReflect/A.class (No such file or directory) -> [Help 1]
    org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.thoughtworks.paranamer:paranamer-maven-plugin:2.8:generate (paranamer-test) on project avro: Failed to generate parameter names from /home/ebourg/avro-java/lang/java/avro/src/test/java
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute (MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main (MavenCli.java:191)
        at org.apache.maven.cli.MavenCli.main (MavenCli.java:180)
        at org.debian.maven.Wrapper.main (Wrapper.java:89)
        at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke (Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard (Launcher.java:330)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:238)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
    Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to generate parameter names from /home/ebourg/avro-java/lang/java/avro/src/test/java
        at com.thoughtworks.paranamer.mojo.ParanamerGeneratorMojo.execute (ParanamerGeneratorMojo.java:97)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute (MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main (MavenCli.java:191)
        at org.apache.maven.cli.MavenCli.main (MavenCli.java:180)
        at org.debian.maven.Wrapper.main (Wrapper.java:89)
        at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke (Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard (Launcher.java:330)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:238)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
    Caused by: java.io.FileNotFoundException: /home/ebourg/avro-java/lang/java/avro/target/test-classes/org/apache/avro/reflect/TestReflect/A.class (No such file or directory)
        at java.io.FileInputStream.open0 (Native Method)
        at java.io.FileInputStream.open (FileInputStream.java:195)
        at java.io.FileInputStream.<init> (FileInputStream.java:138)
        at com.thoughtworks.paranamer.generator.Enhancer.addExtraStaticField (Enhancer.java:61)
        at com.thoughtworks.paranamer.generator.Enhancer.enhance (Enhancer.java:52)
        at com.thoughtworks.paranamer.generator.QdoxParanamerGenerator.processClasses (QdoxParanamerGenerator.java:88)
        at com.thoughtworks.paranamer.generator.QdoxParanamerGenerator.processSourcePath (QdoxParanamerGenerator.java:66)
        at com.thoughtworks.paranamer.mojo.ParanamerGeneratorMojo.execute (ParanamerGeneratorMojo.java:95)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute (MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main (MavenCli.java:191)
        at org.apache.maven.cli.MavenCli.main (MavenCli.java:180)
        at org.debian.maven.Wrapper.main (Wrapper.java:89)
        at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke (Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard (Launcher.java:330)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:238)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)

The TestReflect class has a A inner class, and it looks like TestReflect is now considered as a package name.

**Comment by rfscholte** [comment] 2017-10-22 12:52
Right, this needs to be fixed in Paranamer, see https://github.com/rfscholte/paranamer/blob/master/paranamer-generator/src/java/com/thoughtworks/paranamer/generator/QdoxParanamerGenerator.java#L76

It should use `getBinaryName()` instead of `getFullyQualifiedName()`

**Closed** 2022-10-13 15:25 UTC
