### ISSUE TITLE
Enum Problem 

### ISSUE THREAD

**Issue by jad7** [paul-hammant/qdox#4] opened 2015-07-08 22:37 UTC
Maybe it's similar like https://github.com/paul-hammant/qdox/issues/1 (Exception when parsing Enum with fields)
Please add this to EnumsTest:
 
public void testMethodAnotherEnum()
    {
        String source="package simpleenum;\r\n" +
        		"public enum MinimalEnumExampleMethod\r\n" +
        		"{\r\n" +
                "  ANOTHER_ENUM(SubEnum.SOME),\r\n" +
                "  ANOTHER_ENUM_INVOKE(SubEnum.SCOPE.getName());\r\n" +
        		"  private final SubEnum subEnum;\r\n" +
        		"  private MinimalEnumExampleMethod(final SubEnum subEnum)\r\n" +
        		"  {\r\n" +
        		"    this.subEnum = subEnum;\r\n" +
        		"  }\r\n" +
        		"  private MinimalEnumExampleMethod(final String subEnumString)\r\n" +
        		"  {\r\n" +
        		"    this.subEnum = SubEnum.valueOf(subEnumString);\r\n" +
        		"  }\r\n" +
                "   public enum SubEnum {\r\n" +
                "       SOME;\r\n" +
                "       pubic String getName() { return name();}\r\n" +
                "   }\r\n" +
        		"}\r\n";
        JavaSource javaSource = new JavaProjectBuilder().addSource(new StringReader(source));
    }

**Comment by rfscholte** [comment] 2015-12-30 19:33
I consider this as a duplicate of #1. The documentation of the Java Language Specification is missing this part.

**Closed by rfscholte** 2015-12-30 19:33 UTC
