### ISSUE TITLE
qdox2: testAddEnumWithFieldAndConstructorsToModelBinary fails with Java 9

### ISSUE THREAD

**Issue by apoleon** [paul-hammant/qdox#42] opened 2018-03-19 21:43 UTC
When I try to compile qdox2 from source with OpenJDK 9, the test testAddEnumWithFieldAndConstructorsToModelBinary will fail. The output looks like this

[ERROR] Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.868 s <<< FAILURE! - in com.thoughtworks.qdox.EnumsModelTest
[ERROR] testAddEnumWithFieldAndConstructorsToModelBinary(com.thoughtworks.qdox.EnumsModelTest)  Time elapsed: 0.913 s  <<< FAILURE!
junit.framework.AssertionFailedError
	at com.thoughtworks.qdox.EnumsModelTest.testAddEnumWithFieldAndConstructorsToModelBinary(EnumsModelTest.java:181)

**Comment by rfscholte** [comment] 2018-06-02 14:55
QDox is built with source/target 1.5, which are not supported by JDK9, so cannot reproduce. Also, [Travis CI](https://travis-ci.org/paul-hammant/qdox) seems happy.

**Comment by rfscholte** [comment] 2018-06-02 16:14
Caused by a spec change for `Class.getPackage()`, is now fixed.

**Closed** 2018-06-02 16:13 UTC
